<?php

define('TRANSPARENT_LEVEL', 21);

define('WATERMARK_ORIENTATION','TOPLEFT');
/*
define('WATERMARK_ORIENTATION','TOPCENTER');
define('WATERMARK_ORIENTATION','TOPRIGHT');
define('WATERMARK_ORIENTATION','CENTERLEFT');
define('WATERMARK_ORIENTATION','CENTER');
define('WATERMARK_ORIENTATION','CENTERRIGHT');
define('WATERMARK_ORIENTATION','BOTTOMLEFT');
define('WATERMARK_ORIENTATION','BOTTOMCENTER');
define('WATERMARK_ORIENTATION','BOTTOMRIGHT');
*/


?>